config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations, only: [:create]
      
      resources :sessions, only: [:create]
      delete '/logout/:auth_token' => 'sessions#logout'
      get '/current_user' => 'sessions#current_user'
    end
  end

  constraints subdomain: AppConfig['admin_subdomain'] do
    get '/admin/dashboard' => 'admin/admin#dashboard', as: :admin_dashboard
    namespace 'admin', as: 'admin' do
      resources :accounts
      
    end
  end

  get '/signup/thanks'      => 'welcome#thanks',        as: :thanks
  get '/signup'             => 'welcome#plans',         as: :plans
  get '/dashboard'          => 'base#dashboard',        as: :user_dashboard

  devise_for :users, 
    controllers: {
      sessions: 'users/sessions', 
      confirmations: 'users/confirmations'
  }, skip: [:registrations, :sessions, :passwords]
  as :user do
    get     'signup/:plan',   to: 'users/registrations#new',        as: :new_registration
    post    'signup',         to: "users/registrations#create",     as: :registration

    get     'sessions/new',   to: 'users/sessions#new',             as: :new_session
    post    'sessions/new',   to: 'users/sessions#create',          as: :session
    delete  'logout',         to: 'users/sessions#destroy',         as: :destroy_session
    get     'logout',         to: 'users/sessions#destroy'

    post    'users/password',      to: 'users/passwords#create',     as: :user_password
    get     'users/password/new',  to: 'users/passwords#new',        as: :new_user_password
    get     'users/password/edit', to: 'users/passwords#edit',       as: :edit_user_password
    patch   'users/password',      to: 'users/passwords#update'
    put     'users/password',      to: 'users/passwords#update'

  end

  resources :clinics do
    resources :patients do
      member do
        put 'toggle_active_status'
        get 'add_family_member_for'
      end

      resources :patient_cases do
        resources :patient_visits do
          collection do
            post :diagnosis_chosen
          end
          member do
            put :pull_from_case
            put :push_to_case
            get :diagnoses 
            get :report_option
            post :generate_report
            get :receipt_report
            post :receipt_report
          end
          resources :patient_visit_details
        end
      end            
    end

    resources :appointments do
      collection do
        get :day_at_glance
        get :week_at_glance
        get :report_options
        post :report_options, defaults: {format: :pdf}
      end
    end
  
    resources :procedure_codes do
      collection do
        get :import
        post :type_code_selected
        get :report
        post :generate_report
      end
    end

    resources :patient_bills do
      member do 
        get :hcfa
      end
    end
  end
  resources :patient_reports, only: [:index, :create]
  resources :patients
  
  resources :providers do 
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :letters do
    collection do
      post 'checkUniqueSignName'
      get 'new_import'
      post 'import'      
    end
  end
  
  resources :insurance_carriers do
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :attorneys do
    collection do
      post 'checkUniqueSignName'
      get 'report'
      post 'generate_report'
    end
  end

  resources :referrers do
    collection do
      post 'checkUniqueSignName'
    end
  end
  
  resources :diagnosis_codes do
    collection do
      get   :import
      post  :import_data
      get   :report
      post  :generate_report
    end
  end

  resources :accounts do
    collection do
      get :plan
      post :plan
      get :cancel
      post :cancel
      get :billing
    end
  end
  
  resources :rooms
  root 'welcome#home'

end

app/views/layouts/dashboard/_admin_left_panel.html.erb
<aside class="aside">
  <!-- START Sidebar (left)-->
  <div class="aside-inner">
    <nav data-sidebar-anyclick-close="" class="sidebar">
    <!-- START sidebar nav-->
      <ul class="nav">
        <!-- START user info-->
        <li class="has-user-block">
          <div id="user-block" class="collapse">
            <div class="item user-block">
            <!-- User picture-->
              <div class="user-block-picture">
                <div class="user-block-status">
                  <img src="/assets/dashboard/user/02.jpg" alt="Avatar" width="60" height="60" class="img-thumbnail img-circle">
                </div>
              </div>
              
              <!-- Name and Job-->
              <div class="user-block-info">
                <span class="user-block-name">Hello, <%= current_user.fullname %></span>
                <span class="user-block-role">
                  <%= link_to "LOGOUT", destroy_session_path, method: :delete, data: {disable_with: 'Please wait...'} %>
                </span>
              </div>
            </div>
          </div>
        </li>
        <!-- END user info-->
        <!-- Iterates over all sidebar items-->
        <li class="nav-heading ">
          <span data-localize="sidebar.heading.HEADER">Main Navigation</span>
        </li>
            
        <li class="<%= 'active' if controller.action_name == 'dashboard' && controller.controller_name == 'base' %>">
          <%= link_to admin_dashboard_path, title: 'Dashboard', data: {disable_with: 'Please Wait...'} do %>
            <em class="icon-speedometer"></em>
            <span data-localize="sidebar.nav.DASHBOARD">Dashboard</span>            
          <% end %>
        </li>

        <li class="<%= 'active' if controller.controller_name == 'accounts' %>">
          <%= link_to admin_accounts_path, title: 'Accounts', data: {disable_with: 'Please Wait...'} do %>
            <em class="fa fa-th-large"></em>
            <span data-localize="sidebar.nav.DASHBOARD">Accounts</span>            
          <% end %>
        </li>

      </ul>
      <!-- END sidebar nav-->
    </nav>
  </div>
  <!-- END Sidebar (left)-->
</aside>

app/views/layouts/dashboard/_header.html.erb
<header class="topnavbar-wrapper">
   <!-- START Top Navbar-->
   <nav role="navigation" class="navbar topnavbar">
      <!-- START navbar header-->
      <div class="navbar-header">
         <a href="<%= root_path %>" class="navbar-brand">
            <div class="brand-logo">
               <img src="/assets/dashboard/logo.png" alt="App Logo" class="img-responsive">
            </div>
            <div class="brand-logo-collapsed">
               <img src="/assets/dashboard/logo-single.png" alt="App Logo" class="img-responsive">
            </div>
         </a>
      </div>
      <!-- END navbar header-->
      <!-- START Nav wrapper-->
      <div class="nav-wrapper">
         <!-- START Left navbar-->
         <ul class="nav navbar-nav">
            <li>
               <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
               <a href="javascript:void(0);" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
                  <em class="fa fa-navicon"></em>
               </a>
               <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
               <a href="javascript:void(0);" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                  <em class="fa fa-navicon"></em>
               </a>
            </li>
            <!-- START User avatar toggle-->
            <li>
               <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
               <a id="user-block-toggle" href="#user-block" data-toggle="collapse">
                  <em class="icon-user"></em>
               </a>
            </li>
            <li>
               <%= link_to "<em class='fa fa-sign-out'></em> Logout".html_safe, destroy_session_path, method: :delete, data: {disable_with: 'Please wait...'} %>
            </li>
            <!-- END lock screen-->
         </ul>
         <!-- END Left navbar-->
         <!-- START Right Navbar-->
         <ul class="nav navbar-nav navbar-right">
            <!-- Search icon-->
            <li>
               <a href="javascript:void(0);" data-search-open="">
                  <em class="icon-magnifier"></em>
               </a>
            </li>
            <!-- Fullscreen (only desktops)-->
            <li class="visible-lg">
               <a href="javascript:void(0);" data-toggle-fullscreen="">
                  <em class="fa fa-expand"></em>
               </a>
            </li>
            <!-- START Alert menu-->
            <li class="dropdown dropdown-list">
               <a href="javascript:void(0);" data-toggle="dropdown">
                  <em class="icon-bell"></em>
                  <div class="label label-danger">11</div>
               </a>
               <!-- START Dropdown menu-->
               <ul class="dropdown-menu animated flipInX">
                  <li>
                     <!-- START list group-->
                     <div class="list-group">
                        <!-- list item-->
                        <a href="javascript:void(0);" class="list-group-item">
                           <div class="media-box">
                              <div class="pull-left">
                                 <em class="fa fa-twitter fa-2x text-info"></em>
                              </div>
                              <div class="media-box-body clearfix">
                                 <p class="m0">New followers</p>
                                 <p class="m0 text-muted">
                                    <small>1 new follower</small>
                                 </p>
                              </div>
                           </div>
                        </a>
                        <!-- list item-->
                        <a href="javascript:void(0);" class="list-group-item">
                           <div class="media-box">
                              <div class="pull-left">
                                 <em class="fa fa-envelope fa-2x text-warning"></em>
                              </div>
                              <div class="media-box-body clearfix">
                                 <p class="m0">New e-mails</p>
                                 <p class="m0 text-muted">
                                    <small>You have 10 new emails</small>
                                 </p>
                              </div>
                           </div>
                        </a>
                        <!-- list item-->
                        <a href="javascript:void(0);" class="list-group-item">
                           <div class="media-box">
                              <div class="pull-left">
                                 <em class="fa fa-tasks fa-2x text-success"></em>
                              </div>
                              <div class="media-box-body clearfix">
                                 <p class="m0">Pending Tasks</p>
                                 <p class="m0 text-muted">
                                    <small>11 pending task</small>
                                 </p>
                              </div>
                           </div>
                        </a>
                        <!-- last list item-->
                        <a href="javascript:void(0);" class="list-group-item">
                           <small>More notifications</small>
                           <span class="label label-danger pull-right">14</span>
                        </a>
                     </div>
                     <!-- END list group-->
                  </li>
               </ul>
               <!-- END Dropdown menu-->
            </li>
            <!-- END Alert menu-->
            <!-- START Offsidebar button-->
            <li>
               <a href="javascript:void(0);" data-toggle-state="offsidebar-open" data-no-persist="true">
                  <em class="icon-notebook"></em>
               </a>
            </li>
            <!-- END Offsidebar menu-->
         </ul>
         <!-- END Right Navbar-->
      </div>
      <!-- END Nav wrapper-->
      <!-- START Search form-->
      <form role="search" action="search.html" class="navbar-form">
         <div class="form-group has-feedback">
            <input type="text" placeholder="Type and hit enter ..." class="form-control">
            <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
         </div>
         <button type="submit" class="hidden btn btn-default">Submit</button>
      </form>
      <!-- END Search form-->
   </nav>
   <!-- END Top Navbar-->
</header>

app/views/layouts/dashboard/_language.html.erb
<div class="pull-right">
   <div class="btn-group">
      <button type="button" data-toggle="dropdown" class="btn btn-default">English</button>
      <ul role="menu" class="dropdown-menu dropdown-menu-right animated fadeInUpShort">
         <li><a href="#" data-set-lang="en">English</a></li>
         <li><a href="#" data-set-lang="es">Spanish</a></li>
      </ul>
   </div>
</div>