config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations, only: [:create]
      
      resources :sessions, only: [:create]
      delete '/logout/:auth_token' => 'sessions#logout'
      get '/current_user' => 'sessions#current_user'
    end
  end

  constraints subdomain: AppConfig['admin_subdomain'] do
    get '/admin/dashboard' => 'admin/admin#dashboard', as: :admin_dashboard
    namespace 'admin', as: 'admin' do
      resources :accounts
      
    end
  end

  get '/signup/thanks'      => 'welcome#thanks',        as: :thanks
  get '/signup'             => 'welcome#plans',         as: :plans
  get '/dashboard'          => 'base#dashboard',        as: :user_dashboard

  devise_for :users, 
    controllers: {
      sessions: 'users/sessions', 
      confirmations: 'users/confirmations'
  }, skip: [:registrations, :sessions, :passwords]
  as :user do
    get     'signup/:plan',   to: 'users/registrations#new',        as: :new_registration
    post    'signup',         to: "users/registrations#create",     as: :registration

    get     'sessions/new',   to: 'users/sessions#new',             as: :new_session
    post    'sessions/new',   to: 'users/sessions#create',          as: :session
    delete  'logout',         to: 'users/sessions#destroy',         as: :destroy_session
    get     'logout',         to: 'users/sessions#destroy'

    post    'users/password',      to: 'users/passwords#create',     as: :user_password
    get     'users/password/new',  to: 'users/passwords#new',        as: :new_user_password
    get     'users/password/edit', to: 'users/passwords#edit',       as: :edit_user_password
    patch   'users/password',      to: 'users/passwords#update'
    put     'users/password',      to: 'users/passwords#update'

  end

  resources :clinics do
    resources :patients do
      member do
        put 'toggle_active_status'
        get 'add_family_member_for'
      end

      resources :patient_cases do
        resources :patient_visits do
          collection do
            post :diagnosis_chosen
          end
          member do
            put :pull_from_case
            put :push_to_case
            get :diagnoses 
            get :report_option
            post :generate_report
            get :receipt_report
            post :receipt_report
          end
          resources :patient_visit_details
        end
      end            
    end

    resources :appointments do
      collection do
        get :day_at_glance
        get :week_at_glance
        get :report_options
        post :report_options, defaults: {format: :pdf}
      end
    end
  
    resources :procedure_codes do
      collection do
        get :import
        post :type_code_selected
        get :report
        post :generate_report
      end
    end

    resources :patient_bills do
      member do 
        get :hcfa
      end
    end
  end
  resources :patient_reports, only: [:index, :create]
  resources :patients
  
  resources :providers do 
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :letters do
    collection do
      post 'checkUniqueSignName'
      get 'new_import'
      post 'import'      
    end
  end
  
  resources :insurance_carriers do
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :attorneys do
    collection do
      post 'checkUniqueSignName'
      get 'report'
      post 'generate_report'
    end
  end

  resources :referrers do
    collection do
      post 'checkUniqueSignName'
    end
  end
  
  resources :diagnosis_codes do
    collection do
      get   :import
      post  :import_data
      get   :report
      post  :generate_report
    end
  end

  resources :accounts do
    collection do
      get :plan
      post :plan
      get :cancel
      post :cancel
      get :billing
    end
  end
  
  resources :rooms
  root 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	layout 'frontpage', only: [:home, :plans]

  def index
  end

  def home
  	@plans = Plan.all
  end

  def thanks
  	if session[:domain].present?
  		@domain = session[:domain]
  		session[:domain] = nil
      render layout: 'login'
  	else
  		redirect_to plans_path
  	end  	
  end

  def plans
  	@plans = Plan.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def custom_pluralize(count, string)
		if count.to_i >= 2
			"#{string}s"
		else
			"#{string}"	
		end
	end	

	## Display Error Message On Fields
  def display_error_messages(errors, fields = [])
    error_message = []
    fields.each do |field|
      field_name = field.to_s.split('.').last
      errors.messages[field].each { |error| error_message <<  "#{field_name.to_s.humanize} #{error}" } if errors.messages[field]
    end
    if error_message.size > 1
      (error_message.empty?) ? '' : "#{error_message.first}"
    else
      (error_message.empty?) ? '' : "#{error_message.join(', ')}"
    end
  end
	
  def flash_message(level)
    case level
      when 'notice' 
        return "alert-info"
      when 'success' 
        return "alert-success"
      when 'error' 
        return "alert-danger"
      when 'alert' 
        return "alert-danger"
    end
  end
end

app/views/welcome/_plans.html.erb
<section id="plans" class="plan-table">
  <div class="container">
    <!-- SECTION HEADER-->
    <div data-wow-offset="15" data-wow-duration="1.3s" class="section-header wow fadeIn animated">
      <h2>Plans</h2>
      <div class="section-description">
        30-day free trial, sign up in 60 seconds
      </div>
    </div>
    <!-- END SECTION HEADER-->
    
    <div class="row">
      <!-- PLAN-->
      <% @plans.each do |plan| %>
        <div data-wow-offset="15" data-wow-duration="1.3s" class="col-md-3 col-sm-3 wow fadeIn animated">
          
          <div class="plan" style="margin-bottom: 10px;">
            
            <h3 class="plan-header"><%= plan.try(:name) %></h3>
            
            <div class="plan-price">
              <h2><sup><small>$</small></sup><%= plan.price_with_month %></h2>
            </div>
            
            <ul class="plan-features">
              <li><strong><%= plan.title %></strong></li>
            
              <li>
                <em><%= plan.total_clinic %></em>
                <%= custom_pluralize(plan.total_clinic, 'clinic') %>
              </li>
            
              <li>
                <em class=''><%= plan.total_doctors %></em>
                <%= custom_pluralize(plan.total_doctors, 'doctor') %>
              </li>

              <% if plan.price.to_s != '0' %>
                <li><em class="fa fa-check"></em> Time tracking</li>
                <li><em class="fa fa-check"></em>Enhanced security</li>
              <% else %>
                <li><em class="fa fa-times plan-feature-disable"></em>Time tracking</li>
                <li><em class="fa fa-times plan-feature-disable"></em>Enhanced security</li>
              <% end %>

            </ul>
            
            <hr>
            
            <div class="text-center">
              <%= link_to 'Sign Up', new_registration_path(plan.price_with_dollar), class: 'btn btn-theme', data: {disable_with: 'Loading'} %>
            </div>

          </div>

          <% if controller.controller_name.to_s == 'welcome' && controller.action_name == 'plans' %>
            <div data-wow-offset="15" data-wow-duration="1.3s" class="col-md-3 col-sm-3 wow fadeIn animated" style="width: 100%;padding:0px;">
              <div class="plan">
                <ul class="plan-features">
                  <% plan.plan_facilities.each do |facility| %>
                    <li>
                      <em class="fa fa-plus"></em> 
                      <small class="extra-small"><%= facility.try(:name) %></small>
                    </li>  
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/home.html.erb
<!-- START HEADER-->
<%= render partial: 'layouts/frontend/header' %>
<!-- END HEADER-->

<!-- START APP SHOTS-->
<%#= render partial: 'layouts/frontend/version' %>

<!-- START FEATURE LIST-->
<%#= render partial: 'layouts/frontend/features' %>
<!-- END FEATURE LIST-->

<!-- START PIC TEXT LEFT-->
<%= render partial: 'layouts/frontend/desc2' %>
<!-- END PIC TEXT LEFT-->

<!-- START PIC TEXT RIGHT-->
<%= render partial: 'layouts/frontend/desc1' %>
<!-- END PIC TEXT RIGHT-->

<!-- START APP SHOTS-->
<%#= render partial: 'layouts/frontend/shots' %>
<!-- END APP SHOTS-->

<!-- START TESTIMONIAL SLIDER-->
<%= render partial: 'layouts/frontend/feedbacks' %>
<!-- END TESTIMONIAL SLIDER-->

<!-- START PLAN TABLE-->
<%= render partial: 'plans' %>
<!-- END PLAN TABLE-->
<%= render partial: 'layouts/frontend/contact' %>

<!-- START FOOTER-->
<%= render partial: 'layouts/frontend/footer' %>
<!-- END FOOTER-->

<!-- START SETTINGS-->
<%#= render partial: 'layouts/frontend/settings' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/plans.html.erb
<header id="header" class="header novideo">
  <div class="fullscreen">
    <!-- START STICKY NAVBAR-->
    <div class="navbar navbar-default navbar-fixed-top navbar-sticky">
      <div class="container">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar-main" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">
            <img src="/assets/logo-dark.png" alt="">
          </a>
        </div>
        <!-- MENU-->
        <div id="navbar-main" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right main-navbar">
            <% if current_user.present? %>
              <li><a href="<%= user_dashboard_path %>">Dashboard</a></li>
              <li><%= link_to "Logout", destroy_session_path, method: :delete, data: {disable_with: 'Please wait...'} %></li>
            <% else %>
              <li><a href="<%= new_session_path %>">Login</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- START PLAN TABLE-->
<%= render partial: 'plans' %>

app/views/welcome/thanks.html.erb
<h4>Account Created</h4>
<p>
  Thank you for creating an account!  You can now log in to your account at   
  <%= link_to "http://#{@domain}", "http://#{@domain}" %>.
</p>