config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations, only: [:create]
      
      resources :sessions, only: [:create]
      delete '/logout/:auth_token' => 'sessions#logout'
      get '/current_user' => 'sessions#current_user'
    end
  end

  constraints subdomain: AppConfig['admin_subdomain'] do
    get '/admin/dashboard' => 'admin/admin#dashboard', as: :admin_dashboard
    namespace 'admin', as: 'admin' do
      resources :accounts
      
    end
  end

  get '/signup/thanks'      => 'welcome#thanks',        as: :thanks
  get '/signup'             => 'welcome#plans',         as: :plans
  get '/dashboard'          => 'base#dashboard',        as: :user_dashboard

  devise_for :users, 
    controllers: {
      sessions: 'users/sessions', 
      confirmations: 'users/confirmations'
  }, skip: [:registrations, :sessions, :passwords]
  as :user do
    get     'signup/:plan',   to: 'users/registrations#new',        as: :new_registration
    post    'signup',         to: "users/registrations#create",     as: :registration

    get     'sessions/new',   to: 'users/sessions#new',             as: :new_session
    post    'sessions/new',   to: 'users/sessions#create',          as: :session
    delete  'logout',         to: 'users/sessions#destroy',         as: :destroy_session
    get     'logout',         to: 'users/sessions#destroy'

    post    'users/password',      to: 'users/passwords#create',     as: :user_password
    get     'users/password/new',  to: 'users/passwords#new',        as: :new_user_password
    get     'users/password/edit', to: 'users/passwords#edit',       as: :edit_user_password
    patch   'users/password',      to: 'users/passwords#update'
    put     'users/password',      to: 'users/passwords#update'

  end

  resources :clinics do
    resources :patients do
      member do
        put 'toggle_active_status'
        get 'add_family_member_for'
      end

      resources :patient_cases do
        resources :patient_visits do
          collection do
            post :diagnosis_chosen
          end
          member do
            put :pull_from_case
            put :push_to_case
            get :diagnoses 
            get :report_option
            post :generate_report
            get :receipt_report
            post :receipt_report
          end
          resources :patient_visit_details
        end
      end            
    end

    resources :appointments do
      collection do
        get :day_at_glance
        get :week_at_glance
        get :report_options
        post :report_options, defaults: {format: :pdf}
      end
    end
  
    resources :procedure_codes do
      collection do
        get :import
        post :type_code_selected
        get :report
        post :generate_report
      end
    end

    resources :patient_bills do
      member do 
        get :hcfa
      end
    end
  end
  resources :patient_reports, only: [:index, :create]
  resources :patients
  
  resources :providers do 
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :letters do
    collection do
      post 'checkUniqueSignName'
      get 'new_import'
      post 'import'      
    end
  end
  
  resources :insurance_carriers do
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :attorneys do
    collection do
      post 'checkUniqueSignName'
      get 'report'
      post 'generate_report'
    end
  end

  resources :referrers do
    collection do
      post 'checkUniqueSignName'
    end
  end
  
  resources :diagnosis_codes do
    collection do
      get   :import
      post  :import_data
      get   :report
      post  :generate_report
    end
  end

  resources :accounts do
    collection do
      get :plan
      post :plan
      get :cancel
      post :cancel
      get :billing
    end
  end
  
  resources :rooms
  root 'welcome#home'

end

app/views/layouts/frontend/_contact.html.erb
    <section id="contact" class="contact">
      <div class="container">
         <!-- SECTION HEADER-->
         <div data-wow-offset="15" data-wow-duration="1.3s" class="section-header wow fadeIn animated">
            <h2>Get in contact with Us</h2>
            <div class="text-center">
               <address>
                  <strong>Twitter, Inc.</strong>
                  <br>795 Folsom Ave, Suite 600
                  <br>San Francisco, CA 94107
                  <br>
                  <abbr title="Phone">P:</abbr>(123) 456-7890</address>
            </div>
         </div>
         <div class="row">
            <img src="/assets/contact.map.jpg" alt="Map" data-no-retina class="img-responsive img-rounded">
         </div>
         <!-- SOCIAL SHARE-->
         <ul class="list-icons">
            <li>
               <a href="">
                  <em class="fa fa-twitter-square"></em>
               </a>
            </li>
            <li>
               <a href="">
                  <em class="fa fa-facebook-square"></em>
               </a>
            </li>
            <li>
               <a href="">
                  <em class="fa fa-google-plus-square"></em>
               </a>
            </li>
            <li>
               <a href="">
                  <em class="fa fa-instagram"></em>
               </a>
            </li>
            <li>
               <a href="">
                  <em class="fa fa-flickr"></em>
               </a>
            </li>
            <li>
               <a href="">
                  <em class="fa fa-pinterest-square"></em>
               </a>
            </li>
         </ul>
      </div>
   </section>

app/views/layouts/frontend/_desc1.html.erb
   <section id="desc1" class="pic-text pic-text-right">
      <div class="container">
         <div class="row">
            <!-- LEFT TEXT-->
            <div class="col-md-6">
               <!-- SECTION TITLE-->
               <h2>EMR</h2>
               <p>EMR is a management solution designed for health practitioners. </p>
               <p>It's friendly, easy-to-use interface and user-friendly processes make it a positive addition to your practice.</p>

            </div>
            <!-- RIGHT PIC-->
            <div data-wow-offset="15" data-wow-duration="1.2s" class="col-md-6 wow fadeInRight animated">
               <div class="mockup-mobile">
                  <img src="/assets/iphone-angle.png" alt="" data-no-retina>
               </div>
            </div>
            <!-- /END PHONES IMAGE-->
         </div>
      </div>
   </section>

app/views/layouts/frontend/_desc2.html.erb
   <section id="desc2" class="pic-text pic-text-left">
      <div class="container">
         <div class="row">
            <!-- LEFT PIC-->
            <div data-wow-offset="15" data-wow-duration="1.2s" class="col-md-6 wow fadeInLeft animated">
               <div class="mockup-mobile">
                  <img src="/assets/ipad-air.png" alt="" data-no-retina>
               </div>
            </div>
            <!-- RIGHT TEXT-->
            <div class="col-md-6">
               <!-- SECTION TITLE-->
               <h2>What we do?</h2>
               <p>With an integrated line of software products, business services, and strategic consulting, we help healthcare entities:</p>
               <!-- FEATURE LIST-->
               <ul class="featured-list">
                  <li>
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-info fa-stack-1x fa-inverse"></em>
                     </span>
                     <p>Succeed in providing high-level care</p>
                  </li>
                  <li>
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-info fa-stack-1x fa-inverse"></em>
                     </span>
                     <p>Optimize their revenue</p>
                  </li>
                  <li>
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-info fa-stack-1x fa-inverse"></em>
                     </span>
                     <p>Manage their information</p>
                  </li>
                  <li>
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-info fa-stack-1x fa-inverse"></em>
                     </span>
                     <p>Grow and thrive as a business</p>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </section>

app/views/layouts/frontend/_features.html.erb
   <section id="features" class="features-list">
      <div class="container">
         <!-- START SECTION HEADER-->
         <div data-wow-offset="120" data-wow-duration="1.3s" class="section-header wow fadeIn animated">
            <!-- SECTION TITLE-->
            <h2>Full of Features</h2>
            <div class="section-description">Donec mauris arcu, vestibulum ac hendrerit ut, convallis cursus libero.</div>
         </div>
         <!-- END SECTION HEADER-->
         <div class="row">
            <!-- START FEATURES LEFT-->
            <div class="col-md-4 col-sm-4 features-left">
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-random fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">Responsive Layout</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                  </div>
               </div>
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-rocket fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">Bootstrap UI based</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                  </div>
               </div>
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-crosshairs fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">Cross Platform</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magn.</p>
                  </div>
               </div>
            </div>
            <!-- END FEATURES LEFT-->
            <!-- START MOBILE MOCKUP-->
            <div class="col-md-4 col-sm-4">
               <div data-wow-offset="120" data-wow-duration="1.3s" class="mockup-mobile wow fadeIn animated">
                  <img src="/assets/iphone-minimal.png" alt="" data-no-retina>
               </div>
            </div>
            <!-- END MOBILE MOCKUP-->
            <!-- START FEATURES RIGHT-->
            <div class="col-md-4 col-sm-4 features-right">
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-moon-o fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">Lazy load Assets</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                  </div>
               </div>
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-sitemap fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">UI Router States</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                  </div>
               </div>
               <!-- FEATURE-->
               <div class="feature">
                  <!-- FEATURE ICON-->
                  <div data-wow-offset="15" data-wow-duration="1.3s" class="feature-icon wow fadeIn animated">
                     <span class="fa-stack fa-lg">
                        <em class="fa fa-circle fa-stack-2x"></em>
                        <em class="fa fa-wrench fa-stack-1x fa-inverse"></em>
                     </span>
                  </div>
                  <!-- FEATURE TEXT-->
                  <div class="feature-details">
                     <h4 class="main-color">Great Build Tools</h4>
                     <p>Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                  </div>
               </div>
            </div>
            <!-- END FEATURES RIGHT-->
         </div>
      </div>
   </section>

app/views/layouts/frontend/_feedbacks.html.erb
   <section id="feedbacks" class="feedbacks">
      <div data-wow-offset="15" data-wow-duration="1.3s" class="container wow fadeIn animated">
         <div id="feedback-carousel" class="owl-carousel owl-theme text-center">
            <!-- FEEDBACK-->
            <div class="feedback-client">
               <div class="feedback-client-picture">
                  <img src="/assets/clients/01.jpg" alt="" data-no-retina class="img-thumbnail img-circle">
               </div>
               <div class="feedback-client-msg">Etiam feugiat risus massa. Etiam nisi dui, sodales ut dignissim vitae, eleifend non nisi. Donec ipsum enim, fermentum sed viverra et, vulputate eget libero. Sed elementum venenatis ullamcorper. Phasellus faucibus placerat luctus.</div>
               <div
               class="feedback-client-name">Martin Fowler</div>
            <div class="feedback-client-company">Artist, Ngcompany</div>
         </div>
         <!-- FEEDBACK-->
         <div class="feedback-client">
            <div class="feedback-client-picture">
               <img src="/assets/clients/02.jpg" alt="" data-no-retina class="img-thumbnail img-circle">
            </div>
            <div class="feedback-client-msg">Etiam feugiat risus massa. Etiam nisi dui, sodales ut dignissim vitae, eleifend non nisi. Donec ipsum enim, fermentum sed viverra et, vulputate eget libero. Sed elementum venenatis ullamcorper. Phasellus faucibus placerat luctus.</div>
            <div
            class="feedback-client-name">Mathew Rogers</div>
         <div class="feedback-client-company">Designer, Ngcompany</div>
      </div>
      <!-- FEEDBACK-->
      <div class="feedback-client">
         <div class="feedback-client-picture">
            <img src="/assets/clients/03.jpg" alt="" data-no-retina class="img-thumbnail img-circle">
         </div>
         <div class="feedback-client-msg">Etiam feugiat risus massa. Etiam nisi dui, sodales ut dignissim vitae, eleifend non nisi. Donec ipsum enim, fermentum sed viverra et, vulputate eget libero. Sed elementum venenatis ullamcorper. Phasellus faucibus placerat luctus.</div>
         <div class="feedback-client-name">Bradley Jimenez</div>
         <div class="feedback-client-company">Coder, Ngcompany</div>
      </div>
      </div>
      </div>
   </section>

app/views/layouts/frontend/_footer.html.erb
   <footer id="footer">
      <div class="container">
         <div class="row">
            <div class="col-sm-6">
               <ul class="footer-nav">
                  <li><a href="#header" class="scrollto">Home</a>
                  </li>
                  <!-- <li><a href="#features" class="scrollto">Features</a></li> -->
                  <li><a href="#plans" class="scrollto">Plans</a>
                  </li>
               </ul>
            </div>
            <div class="col-sm-6">
               <!-- COPYRIGHT-->
               <p class="copyright">EMR &copy; 2016</p>
            </div>
         </div>
      </div>
   </footer>

app/views/layouts/frontend/_header.html.erb
   <header id="header" class="header novideo">
      <div class="full-screen">
         <!-- START STICKY NAVBAR-->
         <div class="navbar navbar-default navbar-fixed-top navbar-sticky">
            <div class="container">
               <div class="navbar-header">
                  <button type="button" data-toggle="collapse" data-target="#navbar-main" class="navbar-toggle">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                  </button>
                  <a href="#" class="navbar-brand">
                     <img src="/assets/logo-dark.png" alt="">
                  </a>
               </div>
               <!-- MENU-->
               <div id="navbar-main" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav navbar-right main-navbar">
                     <li><a href="#header">Home</a></li>
<!--                      <li><a href="#features">Features</a></li> --> 
                           <!-- <li><a href="#shots">Shots</a></li> -->
                     <li><a href="#plans">Plans</a></li>
                     <% if current_user.present? %>
                        <li><a href="<%= user_dashboard_path %>">Dashboard</a></li>
                        <li><%= link_to "Logout", destroy_session_path, method: :delete, data: {disable_with: 'Please wait...'} %></li>
                     <% else %>
                        <li><a href="<%= new_session_path %>">Login</a></li>
                        <% if not request.subdomain == 'admin' %>
                          <li><a href="<%= plans_path %>">Register</a></li>
                        <% end %>
                     <% end %>
                  </ul>
               </div>
            </div>
         </div>
         <!-- END STICKY NAVBAR-->
         <div class="container">
            <!-- MAIN LOGO-->
            <div class="top-logo">
               <img src="/assets/logo.png" alt="">
            </div>
            <div class="row">
               <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <!-- INTRO MESSAGE-->
                  <div class="intro-section">
                     <h1 class="intro">EMR - Medical Client Tracker</h1>
                     <h5>EMR</h5>
                     <!-- DEMO BUTTON-->
                     <div class="text-center"><a href="#versions" class="btn btn-lg btn-theme scrollto"><i class="icon-app-download"></i><span>Watch all demos</span></a>
                     </div>
                  </div>
                  <div class="intro-shot">
                     <img src="/assets/header.shot.png" alt="Header shot" data-no-retina="" class="img-responsive">
                  </div>
               </div>
            </div>
         </div>
      </div>
   </header>

app/views/layouts/frontend/_settings.html.erb
   <div class="settings">
      <div class="settings-inner">
         <div class="settings-ctrl">
            <em class="fa fa-cogs"></em>
         </div>
         <div class="settings-content">
            <p>Themes</p>
            <div class="setting-colors">
               <div data-load-css="css/theme-a.css" class="setting-color bg-info checked">
                  <em class="fa fa-check"></em>
               </div>
               <div data-load-css="css/theme-b.css" class="setting-color bg-success">
                  <em class="fa fa-check"></em>
               </div>
               <div data-load-css="css/theme-c.css" class="setting-color bg-purple">
                  <em class="fa fa-check"></em>
               </div>
               <div data-load-css="css/theme-d.css" class="setting-color bg-primary">
                  <em class="fa fa-check"></em>
               </div>
            </div>
            <p>Layout</p>
            <div class="clearfix">
               <p class="pull-left">RTL</p>
               <div class="pull-right">
                  <label for="rtlswitch" class="switch">
                     <input type="checkbox" id="rtlswitch">
                     <span></span>
                  </label>
               </div>
            </div>
         </div>
      </div>
   </div>

app/views/layouts/frontend/_shots.html.erb
   <section id="shots" class="appshots">
      <div class="container">
         <!-- SECTION HEADER-->
         <div class="section-header">
            <h2>App Shots</h2>
            <div class="section-description">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices</div>
         </div>
         <!-- END SECTION HEADER-->
         <div class="row">
            <div id="appshots" class="owl-carousel owl-theme">
               <div class="shot">
                  <a href="/assets/shots/01.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/01.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/03.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/03.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/02.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/02.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/04.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/04.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/01.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/01.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/03.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/03.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/02.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/02.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
               <div class="shot">
                  <a href="/assets/shots/04.jpg" data-lightbox-gallery="appshots">
                     <img src="/assets/shots/04.jpg" alt="App Shot" data-no-retina>
                  </a>
               </div>
            </div>
         </div>
      </div>
   </section>