config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :registrations, only: [:create]
      
      resources :sessions, only: [:create]
      delete '/logout/:auth_token' => 'sessions#logout'
      get '/current_user' => 'sessions#current_user'
    end
  end

  constraints subdomain: AppConfig['admin_subdomain'] do
    get '/admin/dashboard' => 'admin/admin#dashboard', as: :admin_dashboard
    namespace 'admin', as: 'admin' do
      resources :accounts
      
    end
  end

  get '/signup/thanks'      => 'welcome#thanks',        as: :thanks
  get '/signup'             => 'welcome#plans',         as: :plans
  get '/dashboard'          => 'base#dashboard',        as: :user_dashboard

  devise_for :users, 
    controllers: {
      sessions: 'users/sessions', 
      confirmations: 'users/confirmations'
  }, skip: [:registrations, :sessions, :passwords]
  as :user do
    get     'signup/:plan',   to: 'users/registrations#new',        as: :new_registration
    post    'signup',         to: "users/registrations#create",     as: :registration

    get     'sessions/new',   to: 'users/sessions#new',             as: :new_session
    post    'sessions/new',   to: 'users/sessions#create',          as: :session
    delete  'logout',         to: 'users/sessions#destroy',         as: :destroy_session
    get     'logout',         to: 'users/sessions#destroy'

    post    'users/password',      to: 'users/passwords#create',     as: :user_password
    get     'users/password/new',  to: 'users/passwords#new',        as: :new_user_password
    get     'users/password/edit', to: 'users/passwords#edit',       as: :edit_user_password
    patch   'users/password',      to: 'users/passwords#update'
    put     'users/password',      to: 'users/passwords#update'

  end

  resources :clinics do
    resources :patients do
      member do
        put 'toggle_active_status'
        get 'add_family_member_for'
      end

      resources :patient_cases do
        resources :patient_visits do
          collection do
            post :diagnosis_chosen
          end
          member do
            put :pull_from_case
            put :push_to_case
            get :diagnoses 
            get :report_option
            post :generate_report
            get :receipt_report
            post :receipt_report
          end
          resources :patient_visit_details
        end
      end            
    end

    resources :appointments do
      collection do
        get :day_at_glance
        get :week_at_glance
        get :report_options
        post :report_options, defaults: {format: :pdf}
      end
    end
  
    resources :procedure_codes do
      collection do
        get :import
        post :type_code_selected
        get :report
        post :generate_report
      end
    end

    resources :patient_bills do
      member do 
        get :hcfa
      end
    end
  end
  resources :patient_reports, only: [:index, :create]
  resources :patients
  
  resources :providers do 
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :letters do
    collection do
      post 'checkUniqueSignName'
      get 'new_import'
      post 'import'      
    end
  end
  
  resources :insurance_carriers do
    collection do
      post 'checkUniqueSignName'
    end
  end

  resources :attorneys do
    collection do
      post 'checkUniqueSignName'
      get 'report'
      post 'generate_report'
    end
  end

  resources :referrers do
    collection do
      post 'checkUniqueSignName'
    end
  end
  
  resources :diagnosis_codes do
    collection do
      get   :import
      post  :import_data
      get   :report
      post  :generate_report
    end
  end

  resources :accounts do
    collection do
      get :plan
      post :plan
      get :cancel
      post :cancel
      get :billing
    end
  end
  
  resources :rooms
  root 'welcome#home'

end

app/controllers/patient_visits_controller.rb
class PatientVisitsController < BaseController
	
	before_action :find_patient_case, :find_patient, :find_clinic
	before_action :find_patient_visit, only: [:show, :edit, :update, :destroy, :pull_from_case, :push_to_case, :diagnoses, :report_option, :receipt_report, :generate_report]

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Clinics", :clinics_path

	def index
		add_breadcrumb "Patients", clinic_patients_path(@clinic)
		add_breadcrumb 'Patient Cases', clinic_patient_patient_cases_path(@clinic, @patient)		

		@patient_visits = @patient_case.patient_visits

		## Scenario 1 - Search for todays date - patient visit.
		@patient_visit 	= @patient_visits.select{|p| p.visited_at.to_date == Date.current.to_date}.last
		## Scenario 2 - If not found patient visit then redirect to new patient visit page - that will auto added patient visit.
		unless @patient_visit.present?
			redirect_to new_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case)
		end

		## Scenario 3
		if params[:patient_visit_id].present?
			@patient_visit = @patient_case.patient_visits.find_by(id: params[:patient_visit_id])
		end
	end

	def new
		## Auto Build Patient Visit
		@patient_visit = @patient_case.patient_visits.build(visited_at: Time.zone.now)
		@patient_visit.pull_diagnosis_and_dates_from_case(@patient_case.id)
		@patient_visit.save!

		## Auto Build Patient Visit Detail
		@patient_visit_detail = @patient_visit.patient_visit_details.create({
			patient_case_id: @patient_case.id,
			amount_cents: 0,
			place_of_service_code: @clinic.place_of_service,
			units_sold: 1,
			diagnosis_pointer: 'ALL',
			place_of_service_code: 11
		})

		redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case, patient_visit_id: @patient_visit.id )
	end

	def show
		respond_to do |format|
			format.html{render nothing: true}
			format.js
		end
	end

	def create
	end

	def edit
		add_breadcrumb "Patients", clinic_patients_path(@clinic)
		add_breadcrumb 'Patient Cases', clinic_patient_patient_cases_path(@clinic, @patient)		
		add_breadcrumb 'Patient Visit', clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case)
		add_breadcrumb 'Edit'
	end

	def update
		if params[:patient_visit] && @patient_visit.update_attributes(patient_visit_params)
			redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case, patient_visit_id: @patient_visit.id ), notice: 'Successfully updated patient visit information.'
		else
			if @patient_visit.errors.present?
				redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case, patient_visit_id: @patient_visit.id ), flash: {error: @patient_visit.errors.full_messages.join(', ')}
			else
				redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case, patient_visit_id: @patient_visit.id)
			end
		end
	end

	def destroy
		if @patient_visit.can_delete?
			@patient_visit.destroy
			redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case), notice: 'Successfully destroy patient visit information.'
		else
			redirect_to clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case), notice: "Can't destroy patient visit information."
		end
	end

	def diagnosis_chosen
  	if params[:diagnosis_code_id].present?
    	@diagnosis_code = current_account.diagnosis_codes.find(params[:diagnosis_code_id])
    end
    @number = params[:number]
    respond_to do |format|
    	format.html{render nothing: true}
    	format.js{}
    end
  end

  def pull_from_case
  	@patient_visit.pull_from_case
  	respond_to do |format|
  		format.html{render nothing: true}
  		format.js
  		format.json{render json: @patient_visit}
  	end
  end

  def push_to_case
  	@patient_visit.push_to_case
  	respond_to do |format|
  		format.html{render nothing: true}
  		format.js
  		format.json{render json: @patient_visit}
  	end  	
  end

  def diagnoses
		add_breadcrumb "Patients", clinic_patients_path(@clinic)
		add_breadcrumb 'Patient Cases', clinic_patient_patient_cases_path(@clinic, @patient)		
		add_breadcrumb 'Patient Visit', clinic_patient_patient_case_patient_visits_path(@clinic, @patient, @patient_case)
		add_breadcrumb 'Diagnoses'
  end

  def report_option
  end

  def receipt_report
  	if request.get?
  		@patient_visits = @patient_case.patient_visits
  	else
			page_size 		= "A4"
	    page_layout 	= :portrait
	    column_widths = nil
	    fees 					= nil
			title 				= "Receipt report"
			headers 			= ["Description", "CPT code", "Units", "Service", "Paid", "Adjust", "Balance"]
			fees, data 		= PatientVisit.report(params[:patient_visit_id], params)
			report(title, headers, data, page_size, page_layout, column_widths, fees)
  	end
  end

  def generate_report
  	@bills = []
  	case params[:report_type].to_i
  	when 0
  		patient_case = PatientCase.find(params[:patient_case_id])
  		@bills = patient_case.create_bills(current_account)
  	when 1
  		patient_case = PatientCase.find(params[:patient_case_id])
  		@bills = patient_case.create_bills(current_account)
  	when 2
  		patient_case = PatientCase.find_by(slug: params[:patient_case_id])
  		@bills = patient_case.create_bills(current_account)
  	when 3
  		redirect_to receipt_report_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, @patient_visit)
  	when 4
  		redirect_to receipt_report_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, @patient_visit)
  	else
  		redirect_to receipt_report_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, @patient_visit)
  	end
  end

	private

	def find_clinic
		@clinic = @patient.clinic
	end

	def find_patient
		@patient = @patient_case.patient
	end

	def find_patient_case
		@patient_case = PatientCase.find_by(slug: params[:patient_case_id])
	end

	def find_patient_visit
		@patient_visit = PatientVisit.find(params[:id])
	end

	def patient_visit_params
		if params[:patient_visit].present?
			params.require(:patient_visit).permit(:patient_case_id, :visited_at, :fee_slip_number, :onset_at, :first_treated_at, :should_bill_primary, :should_bill_secondary, :should_bill_attorney, :diagnosis1_id, :diagnosis2_id, :diagnosis3_id, :diagnosis4_id, :details, :diagnosis1_description, :diagnosis2_description, :diagnosis3_description, :diagnosis4_description, :primary_patient_bill_id, :secondary_patient_bill_id, :attorney_patient_bill_id)
		end
	end

	def report(title, headers, data, page_size="A4", page_layout=:portrait, column_widths=nil, fees=nil)
		rand = SecureRandom.hex
		name = "receipt_report_#{rand}.pdf"

		Prawn::Document.generate("public/reports/#{name}", :page_size => page_size, :page_layout => page_layout) do |pdf|

      pdf.bounding_box([1, 780], width: 300, height: 70) do
        pdf.text_box(data[:title], size: 10, style: :bold)
  			pdf.text_box(data[:title2], size: 10, style: :bold)
      end

      pdf.text_box("Date \n" + data[:date], size: 10, style: :bold, at: [10*37, 780])

			unless fees.nil?
				fees_with_headers = [headers] + fees				
				pdf.table(fees_with_headers, cell_style: { size: 7, align: :left, column_widths: column_widths, border_width: 1,  at: [14*32, 780]} )
			end

			pdf.move_down (1*32)

			pdf.text_box(data[:onset], size: 10, at: [0, pdf.move_down(1*32)])
			pdf.text_box(data[:first_treatment], size: 10, at: [0, pdf.move_down(1*32)])
			if data[:visit_patient_owes].present?
				pdf.text_box(data[:visit_patient_owes], size: 10, at: [0, pdf.move_down(1*32)])
			end
			if data[:account_balance].present?
				pdf.text_box(data[:account_balance], size: 10, at: [0, pdf.move_down(1*32)])
			end
			pdf.text_box(data[:account_patient_owes], size: 10, at: [0, pdf.move_down(1*32)])
			pdf.text_box("Diagnosis information:", size: 10, style: :bold, at: [0, pdf.move_down(1*32)])
			pdf.text_box(data[:diagnosis1], size: 10, at: [0, pdf.move_down(1*32)])
			pdf.text_box(data[:diagnosis2], size: 10, at: [0, pdf.move_down(1*32)])
			pdf.text_box(data[:diagnosis3], size: 10, at: [0, pdf.move_down(1*32)])
			pdf.text_box(data[:diagnosis4], size: 10, at: [0, pdf.move_down(1*32)])
		end
		redirect_to "/reports/#{name}"
	end
end

app/helpers/patient_visits_helper.rb
module PatientVisitsHelper
end

app/views/patient_visits/_fee_schedule_label.html.erb
<div class="panel panel-default">
  <div id="FSLabel" role="tab" class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#fslabel1" aria-expanded="" aria-controls="patientcaseOne" class="">
        Fee Schedule Label
      </a>
    </h4>
  </div>

  <div id="fslabel1" role="tabpanel" aria-labelledby="patientHeadingOne" class="panel-collapse collapse" aria-expanded="" style="">
    <div class="panel-body">
    	<%= form_for [@clinic, @patient, @patient_case], html: {class: 'form-inline'}, data: {'parsley-validate': ''}, novalidate: '' do |form| %>
        <%= hidden_field_tag :clinic_id, @clinic.slug %>
        <%= hidden_field_tag :patient_id, @patient_case.patient.slug %>
        <div class="form-group">
          <label for="input-fee-schedule-id" class="sr-only">Fee Schedule Label</label>
          <%= form.select :fee_schedule_label_id, current_account.fee_schedule_labels.map { |l| [ l.label, l.id ] }, {include_blank: 'Select Fee Schedule Label'}, {class: 'form-control m-b'} %>
        </div>
        
        <%= form.submit 'Save', class: 'btn btn-primary', data: { disable_with: "Please Wait..." } %>

      <% end %>
    </div>
  </div>
</div>				

app/views/patient_visits/_visit_lists.html.erb
<div class="panel panel-default">
  <div id="patientVisit2" role="tab" class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#Visit2" aria-expanded="true" aria-controls="Visit2" class="patient-visit-date-header">
        Detail - <%= Time.zone.now.strftime('%d/%m/%Y') %>
      </a>
    </h4>
  </div>
  
  <div id="Visit2" role="tabpanel" aria-labelledby="patientVisit2" class="panel-collapse collapse in" aria-expanded="" style="">
    <div class="panel-body">
        <div id="patient_visit_details">
          <%= render partial: '/patient_visit_details/pv_details' %>
        </div>

        <div class="clearfix"></div><hr>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Dates</th>
                <th>Charges</th>
                <th>Payment</th>
                <th>Adjusted</th>
                <th>Pat Owes</th>
                <th>Insur. Bal.</th>
                <th>Balance</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @patient_visits.each do |visit| %>
                <tr class='patient_visit_<%= visit.id %>'>
                  <td>                    
                    <label class="radio-inline c-radio">                      
                      <%= radio_button_tag 'patient_visit_id', visit.id, visit.id == params[:patient_visit_id].to_i || (@patient_visit && visit.id == @patient_visit.id), onclick: "loadVisit('#{@clinic.slug}', '#{@patient.slug}', '#{@patient_case.slug}', '#{visit.id}');" %>
                      <span class="fa fa-circle"></span>
                    </label>
                  </td>
                  <td><%= visit.visited_at.to_date.strftime('%d/%m/%Y') %></td>
                  <td>$ <%= visit.total_service %></td>
                  <td>$ <%= visit.total_paid %></td>
                  <td>$ <%= visit.total_adjust %></td>
                  <td>$ <%= visit.total_patient_owes %></td>
                  <td>$ <%= visit.total_insurance_owes %></td>
                  <td>$ <%= visit.balance_in_dollars %></td>
                  <td>
                    <%= link_to edit_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, visit), class: 'btn btn-primary btn-xs', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>".html_safe}, title: 'Edit' do %>
                      <i class="fa fa-pencil"></i>
                    <% end %>
                                        
                    <%= link_to clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, visit), class: 'btn btn-danger btn-xs', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>".html_safe, klass: "patient_visit_#{visit.id}", confirm: 'Are you sure want to delete?'}, method: :delete do  %>
                      <em class='fa fa-trash'></em>
                    <% end %>
                    
                    <%= link_to 'PUSH', 'javascript:void(0);', class: "btn btn-info btn-xs", id: "push_to_case_#{visit.id}", title: 'Push To Case Diagnosis', onclick: "pushToCase('#{visit.id}', '#{@clinic.slug}', '#{@patient.slug}', '#{@patient_case.slug}')" %>
                    <%= link_to 'PULL', 'javascript:void(0);', class: "btn btn-info btn-xs", id: "pull_from_case_#{visit.id}", title: 'Pull From Case Diagnosis', onclick: "pullFromCase('#{visit.id}', '#{@clinic.slug}', '#{@patient.slug}', '#{@patient_case.slug}')" %>
                    <%= link_to 'Diagnosis', diagnoses_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, visit), class: "btn btn-info btn-xs", title: 'Diagnosis', data: {disable_with: 'Wait...'} %>
                    <%= link_to "<em class='icon-layers'></em>".html_safe, report_option_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, visit), class: 'btn btn-info btn-xs', data: {disable_with: 'Please Wait...'}, title: 'Report for patient visit.' %>

                  </td>
                </tr>
              <% end %>
              <% if not @patient_visits.nil? %>
                <tr>
                  <td></td>
                  <td><strong> Patient Total Visits <%= h @patient_visits.size %></strong></td>
                  <td>$ <%= @patient_visits.map(&:total_service).sum %></td>
                  <td>$ <%= @patient_visits.map(&:total_paid).sum %></td>
                  <td>$ <%= @patient_visits.map(&:total_adjust).sum %></td>
                  <td>$ <%= total_patient_owes = @patient_visits.map(&:total_patient_owes).sum %></td>
                  <td>$ <%= total_insurance_owes = @patient_visits.map(&:total_insurance_owes).sum %></td>
                  <td>$ <%= total_patient_owes + total_insurance_owes %></td>
                  <td></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        

    </div>
  </div>
</div> 

app/views/patient_visits/diagnoses.html.erb
<h3>Diagnosis
  <ol class="breadcrumb pull-right">
    <%= render_breadcrumbs tag: :li, separator: '' %>
  </ol>
  <small>
  	The purpose of the Transactions form is to record and view services and payments. The top portion of the form is the treatment detail section, which displays the treatments or payments for the current patient visit. At the bottom of transaction form is the transaction history section.
  </small>
</h3>

<div class="panel-body">
  <div class="panel panel-default">
    <div class="panel-body">
    	<%= render partial: '/patient_visits/diagnosis' %>
    </div>
  </div>
</div>

app/views/patient_visits/diagnosis_chosen.js.erb
<% if @diagnosis_code.present? %>
	$('#patient_visit_diagnosis' + '<%= @number %>' + '_description').val('<%= @diagnosis_code.description %>')
<% else %>	
	$('#patient_visit_diagnosis' + '<%= @number %>' + '_description').val('')
<% end %>

app/views/patient_visits/generate_report.html.erb
<h3>Bills
  <ol class="breadcrumb pull-right">
    <%= render_breadcrumbs tag: :li, separator: '' %>
  </ol>
  <small></small>
</h3>
<div class="panel-body">
  <div class="panel panel-default">              
    <div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover">
					<tbody>
						<% @bills.each do |b| %>	
							<tr>
								<td><%= link_to 'Bill #' + + b.id.to_s , hcfa_clinic_patient_bill_path(@clinic, b.id) %></td>
							</tr>
						<% end %>					
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/patient_visits/index.html.erb
<h3>
  Patient Visits - <strong><%= "#{@patient_case.patient.name} - #{@patient_case.description}" %></strong>
  <ol class="breadcrumb pull-right">
    <%= render_breadcrumbs tag: :li, separator: '' %>
  </ol>
  <small>
    The purpose of the Transactions form is to record and view services and payments. The top portion of the form is the treatment detail section, which displays the treatments or payments for the current patient visit. At the bottom of transaction form is the transaction history section.
  </small>
</h3>

<div class="row">
  <div class="col-lg-12 text-right">
    <%= link_to "<em class='fa fa-plus'></em> Add Patient Visit".html_safe, new_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case), class: 'btn btn-info btn-xs pull-right', data: {disable_with: 'Please wait...'} %>    
    <%= link_to "<em class='fa fa-calendar'></em> Appointments".html_safe, clinic_appointments_path(@clinic), class: 'btn btn-info btn-xs pull-right mrgrgt5', data: {disable_with: 'Please wait...'}  %>
  </div>
  <div class="clearfix"></div> 

	<div class="panel-body">
		<div id="accordion" role="tablist" aria-multiselectable="true" class="panel-group">
	  	<%= render partial: '/patient_visits/fee_schedule_label' %>
	  	<%= render partial: '/patient_visits/visit_lists' %>
	  </div>
	</div>

</div>

app/views/patient_visits/report_option.html.erb
<h3>Report
  <ol class="breadcrumb pull-right">
    <%= render_breadcrumbs tag: :li, separator: '' %>
  </ol>
  <small></small>
</h3>
<div class="panel-body">
  <div class="panel panel-default">              
    <div class="panel-body">
      <%= form_tag generate_report_clinic_patient_patient_case_patient_visit_path(@clinic, @patient, @patient_case, @patient_visit), class: 'form-horizontal' do |form| %>
      	<div class='col-md-12'>
          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 0, false, disabled: !@patient_case.billable_visits? %>
	              <span class="fa fa-circle"></span> Create a New HCFA that has only THIS VISIT on it
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 1, false, disabled: !@patient_case.billable_visits? %>
	              <span class="fa fa-circle"></span> REPRINT the existing HCFA that the visit appears
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 2 %>
	              <span class="fa fa-circle"></span> Gather all unbilled visits for THIS CASE on HCFA
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 3, true %>
	              <span class="fa fa-circle"></span> Print Statements
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 4 %>
	              <span class="fa fa-circle"></span> Print a Visit Receipt
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 5 %>
	              <span class="fa fa-circle"></span> Daysheets
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 6 %>
	              <span class="fa fa-circle"></span> Print Soap notes
	            </label>          		
          	</div>
          </div>

          <div class="form-group">
          	<label class="col-lg-1 control-label"></label>
          	<div class="col-lg-10" style="padding-left:20px;">
	            <label class="radio-inline c-radio">
	            	<%= radio_button_tag 'report_type', 7 %>
	              <span class="fa fa-circle"></span> Payment Analysis
	            </label>          		
          	</div>
          </div>

        </div>

        <div class="clearfix"></div>
        <hr>

        <div class="form-group">
          <div class="col-sm-4 col-sm-offset-3">
            <%= link_to 'Cancel', :back, class: 'btn btn-default', data: {disable_with: 'Please Wait...'} %>
            <%= submit_tag 'Generate Report', class: 'btn btn-primary', data: {disable_with: 'Loading...' } %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>